# mass-updates.yml

- name: Login to all hosts (in inventory) in order to collect Ansible Facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Create dynamic host groups based on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- name: Update shared database servers
  hosts: dbs
  become: yes
  gather_facts: no
  serial: 1
  vars:
    systems_to_reboot: []

    # Disallow rebooting by default since this db server provides service
    # for multiple systems
    allow_reboot: false
  tasks:
    - name: Apply mass-updates role
      import_role:
        name: mass-updates

- name: Update test systems, exclude key systems
  hosts: testing:!monitoring:!dbs
  become: yes
  gather_facts: no
  vars:
    systems_to_reboot: []

    # rebooting these systems should be safe enough, provided
    # that we do not run this playbook during prime business hours
    allow_reboot: true
  tasks:
    - name: Apply mass-updates role
      import_role:
        name: mass-updates

- name: Update core systems (skip groups already processed)
  hosts: tier1:!monitoring:!dbs
  become: yes
  gather_facts: no
  vars:
    systems_to_reboot: []

    # rebooting these systems should ideally only be done during scheduled
    # maintenance windows
    allow_reboot: false
    update_core_servers: false
  tasks:
    - name: Apply mass-updates role
      include_role:
        name: mass-updates
      # Defaults to false. This has to be overriden at command-line to run.
      when: update_core_servers
